source "https://rubygems.org"
ruby "3.3.0"

gem "rails", "~> 7.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "jbuilder"
gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "image_processing", "~> 1.2"
gem "active_storage_validations"
gem "resend"

group :development, :test do
  gem "debug", platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "rubocop-rails-omakase", require: false
  gem "letter_opener"
end
